### ISSUE TITLE
Create Yolk.registerElement

### ISSUE THREAD

**Issue by garbles** [yolkjs/yolk#18]
To be able to create custom elements. Something like the following:

```js
Yolk.registerElement(MyCustomComponent, 'my-custom-tag-name')
```

And then someone could just use it in the DOM.

```html
<my-custom-tag-name prop="55"></my-custom-tag-name>
```

**Comment by jadbox** [comment]
Def useful! I like how you think :]

**Comment by garbles** [comment]
Completed with https://github.com/yolkjs/yolk/pull/21
