### ISSUE TITLE
Fork virtual-dom

### ISSUE THREAD

**Issue by garbles** [yolkjs/yolk#20]
- Not using all of the features of `virtual-dom` (too big)
- There many optimizations that I could make (for my specific use case)
- Need to add a few small features (for my specific use case)

**Comment by adicirstei** [comment]
Hi @garbles, 

I really like the minimalist and easy to use API of yolk. Thanks for making the effort to put it together!

Do you plan to remove `virtual-dom` as a dependency?

I have a question regarding [your presentation](http://toothsome-sisters.surge.sh/#/1) only tangentially related to this issue. In the presentation all your examples user use JSX React components. Can you share an example with `virtual-dom`?

**Comment by garbles** [comment]
Hi @adicirstei,

I'm planning to _replace_ `virtual-dom` with [this](https://github.com/yolkjs/yolk-virtual-dom) or a better solution. There are a few optimizations that I'm able to make for the Yolk use case. For example, I don't need Thunks or the ability to parse tags.

The examples in the presentation use JSX, but not React. Unfortunately JSBin does not allow me to specify the JSX Pragma so it defaults to `React.createElement`. Hidden on the HTML panel of each of those bins, you'll see that I had to say `React.createElement = Yolk.createElement`.

**Comment by garbles** [comment]
Completed here: https://github.com/yolkjs/yolk/pull/23
