### ISSUE TITLE
Separating intent/interaction from view components

### ISSUE THREAD

**Issue by jadbox** [yolkjs/yolk#22]
If you look at this example:

[TodoItem.jsx](https://github.com/yolkjs/yolk-todomvc/blob/master/js/TodoItem.js)
```<input className="toggle" type="checkbox" checked={completed} onChange={toggleComplete} />```

What would be the best way for the view component to not have to explicitly state the onChange event on the jsx markup.The end goal is to keep the markup as clean as possible: perhaps allowing a designer to continue to provide new markup without knowledge of the system/yolk being developed around it.

I'm thinking about this from the position on how Cycle uses Intent to keep the raw view tags divorced from being tied to interaction hooks.

**Comment by garbles** [comment]
> What would be the best way for the view component to not have to explicitly state the onChange event on the jsx markup. The end goal is to keep the markup as clean as possible

Can you explain why this would be necessary (aside from saving the designer a bit of confusion)? I would much rather be explicit with what controls an input has access to by inlining those accesses with the markup itself. I've never been a fan of implicit behaviours.

**Comment by jadbox** [comment]
Our designer (who knows little JS) is on contract and needs to work indepentantly on the raw templates, seperate from whatever dynamic logic is that sits on top. I think this is also somewhat important to keep a clean line between static html/css and the (complex) behavors that plugs into it.

**Comment by garbles** [comment]
I see. Unfortunately, like I said, I have a pretty strong preference to inlining those function calls. You could try writing a template and then wrapping it in a [widget](https://github.com/Matt-Esch/virtual-dom/blob/master/docs/widget.md) to get your desired behaviour, i.e. query the subtree for specific classes and then setup your handlers in that way.

Something like:

```js
function SomeComponent () {
 const handleClick = this.createEventListener()   

  // where Cycleify returns a virtual-dom widget
  return new Cycleify({
      '.click-me': [handleClick, 'click']
    },
    <div>
      <button className="click-me">Click</button>
    </div>
  )
}
```

I know that this is not the Cycle way of doing it, but it's the best way I can imagine right now.

**Comment by garbles** [comment]
I should elaborate and say that yolk will work with any custom virtual-dom widget. Right now you have to manually create the widget, but it will be easier once [this has been implemented](https://github.com/yolkjs/yolk/issues/16).

**Comment by jadbox** [comment]
"Cycleify" would solve the use-case just fine I think. I'm not familiar with virtual-dom and widgets, but I'll look into it.

**Comment by garbles** [comment]
Cool. Have we resolved this issue then?

**Comment by jadbox** [comment]
Do you know of anything that fullfils the Cycleify spec? If not, I'll create a utility and perhaps do a merge request to yolk-utils, if that sounds good. Feel free to close then.
