### ISSUE TITLE
Use Proxy if supported

### ISSUE THREAD

**Issue by garbles** [yolkjs/yolk#24]
It would be nice to use this feature if there is browser support for it. Right now, `createEventListener` copies the entire prototype of a ReplaySubject on to a plain function. Due to browser limitations Proxy can't be polyfilled.

https://kangax.github.io/compat-table/es6/#test-Proxy

**Comment by jadbox** [comment]
Why does createEventListener need to make a copy (or Proxy) of ReplaySubject's proto? Perhaps there is an alternative strategy.

**Comment by garbles** [comment]
It needs to copy the prototype because createEventListener must return a function AND the function must behave exactly like an observable. This weird behaviour is one of the keys to making yolk so simple.

In the past I had considered just creating a ReplaySubject and then adding a flag to it - `handler._isEventListener` or something - but then we need to check for it all over the place because observables are destroyed by the `wrapObject` module. Additionally consider that plain functions should also still work with `onX` props, so then we have to have two behaviours for handling events. To me this complexity outweighs the benefit of any extra speed.

Being able to create a new Observable and proxy calls on the function would be very quick. Proxies [can be called as functions](http://ecma-international.org/ecma-262/6.0/#sec-proxycreate).

**Comment by jadbox** [comment]
Cool, makes sense. Also, had no idea that Proxies can be called as functions, neat!

**Comment by garbles** [comment]
Works if I change

```js
addProperties(handler, Rx.ReplaySubject.prototype)
Rx.ReplaySubject.call(handler, 1)
```

to this

```js
if (global.Proxy) {
  const subject = new Rx.ReplaySubject(1)

  handler = new Proxy(handler, {
    get (target, key) {
      return (target[key] !== undefined ? target[key] : subject[key])
    },
    set (__target, key, value) {
      subject[key] = value
      return true
    },
  })
} else {
  addProperties(handler, Rx.ReplaySubject.prototype)
  Rx.ReplaySubject.call(handler, 1)
}
```

No noticeable difference in speed though, so leaving it out for now. I guess I would rather not change the implementation on a per-browser basis.
