### ISSUE TITLE
data-value attribute

### ISSUE THREAD

**Issue by jadbox** [yolkjs/yolk#27]
I'm using a library that I prefer not to fork that requires ```data-value``` attributes on nodes. However, it seems they are filtered out (virtualdom?). Can we support this value though some jsx propererty, for example like ```dataValue```?

**Comment by garbles** [comment]
Added a note to the documentation about adding data attributes https://github.com/yolkjs/yolk#supported-attributes

**Comment by geekytime** [comment]
Was this broken in the rewrite? I can't get `data-value` attributes to show up in the DOM at all.

**Comment by garbles** [comment]
100% broken. Gotta add it back.

**Comment by geekytime** [comment]
Could we just change [NodeProxy.js#L80](https://github.com/garbles/yolk/blob/master/src/NodeProxy.js#L80) from:

```
if (!descriptor) {
      set(node, key, value)
      return
}
```

To:

```
if (!descriptor) {
      node.setAttribute(key, value);
      return;
}
```

Or would that break other things?

**Comment by geekytime** [comment]
There's also the new data api to consider, I suppose... And `aria` attributes.

**Comment by geekytime** [comment]
Meh. It also looks like it'll break other things. I've got spans rendering a `textcontent` attribute, etc.

**Comment by garbles** [comment]
[This](https://github.com/garbles/yolk/commit/7cb3b97dad816c8bf4eab49af3f9a621306e3455) fixes the issue. Added a test for it too.
