### ISSUE TITLE
Why the backticks?

### ISSUE THREAD

**Issue by tudorilisoi** [yolkjs/yolk#37]
I noticed you use es6 string templates (e.g  \`rx\`) instead of string literals 'rx' or "rx" throughout the code
May I ask why is that?

**Comment by garbles** [comment]
Good question. It's purely a style thing. I want all of the strings to follow the same formatting for consistency. By only using backticks, I get string interpolation for free.

**Comment by tudorilisoi** [comment]
Ok, thank you for the clarification.
