### ISSUE TITLE
Proper way to pass event handlers to children?

### ISSUE THREAD

**Issue by ckknight** [yolkjs/yolk#7]
I'd like to separate my components into smart (knowing about stores and actions) and dumb (only interacting with the props passed into it).

One conundrum I ran into is that there doesn't seem to be a straight-forward mechanism to enable passing either a function or an event handler to another component.

The best I came up with was the following:

```js
const COLORS = ['red', 'green', 'blue'];

export default function Color(props) {
    const options = props.selected
        .flatMapLatest(selected => Rx.Observable.from(COLORS)
            .map(color => <option value={color} selected={selected === color}>{color}</option>)
            .toArray());

    const changeHandler = this.createEventHandler();
    changeHandler
        .map(ev => ev.target.value)
        .withLatestFrom(props.onChange,
            (value, onChange) => onChange(value))
        .subscribe();
    
    return (
        <select onChange={changeHandler}>
            {options}
        </select>
    );
}
```

Where it is intended to be used as such:

```js
const colorChangeHandler = this.createEventHandler();
const currentColor = colorChangeHandler.startWith('red');
return <Color selected={currentColor} onChange={colorChangeHandler} />
```

The use of `withLatestFrom` is doable, it just feels awkward, especially with the need to `.subscribe` manually.

**Comment by garbles** [comment]
Yea I think that's probably the correct way to do it right now. You could also do the following to get rid of the empty subscriber at the end.

```js
changeHandler.combineLatest(props.onChange).subscribe(([value, onChange]) => onChange(value));
```

Made a jsbin incase you'd like to discuss further. http://jsbin.com/xedizatiqe/edit?js,output

**Comment by garbles** [comment]
Correction. Because the event handlers also behave as subjects, you can simply say

```js
changeHandler.subscribe(props.onChange)
```

I didn't even realize this until now. :tada:

**Comment by ckknight** [comment]
I'm now suggesting this issue should be a placeholder for adding this information to the README or other public documentation.

**Comment by ckknight** [comment]
Your code causes `Uncaught TypeError: self.observer.onNext is not a function` in Chrome.

**Comment by garbles** [comment]
Weird. Seems to be working fine in the jsbin I posted.

**Comment by ckknight** [comment]
Yep, Just tried in Safari and Firefox. To reproduce the bug, just change the select box from "green" to "blue".

**Comment by garbles** [comment]
Haha wow. I guess `withLatestFrom` is the best option.
![facepalm](http://vignette2.wikia.nocookie.net/fossils-archeology/images/f/f6/640px-Annoyed-facepalm-picard-l.png/revision/latest?cb=20141214203128)

**Comment by garbles** [comment]
I'm thinking I could add a flat `_eventHandler` or something which I could check for when parsing props.

**Comment by ckknight** [comment]
Hmm, I could see that working reasonably well.

**Comment by garbles** [comment]
I think I'll leave it as is for now, but leave this issue open for discuss. Though I like the idea of being able to do something like `changeHandler.subscribe(props.onChange)`, I also don't like the idea of making exceptional cases for specific kinds of props.

**Comment by ckknight** [comment]
Perhaps, but I think some accommodation for a very typical use case could be warranted. Don't avoid sugar for the sake of it, as long as you can find a way not to compromise the core fundamentals.

**Comment by garbles** [comment]
If you can think of a decent helper function to alleviate this issue, it might be worth adding it here https://github.com/yolkjs/yolk-utils

**Comment by ckknight** [comment]
@garbles: no solution from you, then?

**Comment by garbles** [comment]
@ckknight nope. i don't think that there's anything to be fixed.
